// This file was generated by the Sentry wizard because we couldn't find a root layout file.
// You can delete this file at any time.
import { Analytics } from '@vercel/analytics/next'
import { SpeedInsights } from '@vercel/speed-insights/next'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>{children}</body>
      <Analytics />
      <SpeedInsights />
    </html>
  )
}
