import { Block } from 'payload'
import {
  AccordionAtom,
  AlertAtom,
  AvatarAtom,
  BadgeAtom,
  ButtonAtom,
  CardAtom,
  CarouselAtom,
  IconAtom,
  ImageAtom,
  ProgressAtom,
  SeparatorAtom,
  TableAtom,
  TabsAtom,
  TextAtom,
  VideoAtom,
} from '@/blocks/Composable/Atoms/config'

export const AtomBlocks: Block[] = [
  TextAtom,
  ButtonAtom,
  BadgeAtom,
  AlertAtom,
  ImageAtom,
  CardAtom,
  AccordionAtom,
  TabsAtom,
  CarouselAtom,
  AvatarAtom,
  SeparatorAtom,
  ProgressAtom,
  TableAtom,
  IconAtom,
  VideoAtom,
]
