/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    experiments: Experiment;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    experiments: ExperimentsSelect<false> | ExperimentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'ar' | 'bn-IN' | 'hi-IN')
    | ('en' | 'ar' | 'bn-IN' | 'hi-IN')[];
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'en' | 'ar' | 'bn-IN' | 'hi-IN';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  parent?: (string | null) | Page;
  fullSlug?: string | null;
  title: string;
  layout?:
    | (
        | BannerBlock
        | {
            trackId?: string | null;
            title?: string | null;
            cards?:
              | {
                  title?: string | null;
                  content?: string | null;
                  /**
                   * Lucide icon name
                   */
                  icon?: string | null;
                  span?: ('1' | '2' | 'row-2') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bentoGrid';
          }
        | {
            container?:
              | {
                  width?: ('container' | 'wide' | 'full') | null;
                  padding?: ('none' | 'small' | 'medium' | 'large') | null;
                  areas?:
                    | {
                        justify?: ('start' | 'center' | 'end' | 'between' | 'around' | 'evenly') | null;
                        align?: ('start' | 'center' | 'end' | 'stretch' | 'baseline') | null;
                        /**
                         * Gap in pixels
                         */
                        gap?: number | null;
                        items?:
                          | {
                              responsiveWidth?: {
                                base?: ('auto' | 1 | 2 | 3 | 4 | 6 | 8 | 9 | 12) | null;
                                sm?: ('auto' | 1 | 2 | 3 | 4 | 6 | 8 | 9 | 12) | null;
                                md?: ('auto' | 1 | 2 | 3 | 4 | 6 | 8 | 9 | 12) | null;
                                lg?: ('auto' | 1 | 2 | 3 | 4 | 6 | 8 | 9 | 12) | null;
                                xl?: ('auto' | 1 | 2 | 3 | 4 | 6 | 8 | 9 | 12) | null;
                              };
                              content?:
                                | (
                                    | {
                                        items?:
                                          | {
                                              title?: string | null;
                                              content?: string | null;
                                              id?: string | null;
                                            }[]
                                          | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'accordionAtom';
                                      }
                                    | {
                                        title?: string | null;
                                        description?: string | null;
                                        variant?: ('default' | 'destructive') | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'alertAtom';
                                      }
                                    | {
                                        direction?: ('row' | 'column') | null;
                                        justify?: ('start' | 'center' | 'end' | 'between' | 'around' | 'evenly') | null;
                                        align?: ('start' | 'center' | 'end' | 'stretch' | 'baseline') | null;
                                        /**
                                         * Gap in pixels
                                         */
                                        gap?: number | null;
                                        items?:
                                          | (
                                              | {
                                                  label: string;
                                                  url?: string | null;
                                                  variant?:
                                                    | ('default' | 'secondary' | 'outline' | 'ghost' | 'destructive')
                                                    | null;
                                                  id?: string | null;
                                                  blockName?: string | null;
                                                  blockType: 'buttonAtom';
                                                }
                                              | {
                                                  /**
                                                   * Lucide icon name
                                                   */
                                                  iconName?: string | null;
                                                  size?: number | null;
                                                  /**
                                                   * Tailwind class or Hex
                                                   */
                                                  color?: string | null;
                                                  id?: string | null;
                                                  blockName?: string | null;
                                                  blockType: 'iconAtom';
                                                }
                                              | {
                                                  /**
                                                   * Select a preset spacing value, or choose "None" to set custom values
                                                   */
                                                  spacing?: ('none' | '8' | '16' | '24') | null;
                                                  top?: number | null;
                                                  bottom?: number | null;
                                                  left?: number | null;
                                                  right?: number | null;
                                                  id?: string | null;
                                                  blockName?: string | null;
                                                  blockType: 'spacerAtom';
                                                }
                                              | {
                                                  content?: {
                                                    root: {
                                                      type: string;
                                                      children: {
                                                        type: any;
                                                        version: number;
                                                        [k: string]: unknown;
                                                      }[];
                                                      direction: ('ltr' | 'rtl') | null;
                                                      format:
                                                        | 'left'
                                                        | 'start'
                                                        | 'center'
                                                        | 'right'
                                                        | 'end'
                                                        | 'justify'
                                                        | '';
                                                      indent: number;
                                                      version: number;
                                                    };
                                                    [k: string]: unknown;
                                                  } | null;
                                                  align?: ('left' | 'center' | 'right') | null;
                                                  id?: string | null;
                                                  blockName?: string | null;
                                                  blockType: 'textAtom';
                                                }
                                            )[]
                                          | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'alignerAtom';
                                      }
                                    | {
                                        image?: (string | null) | Media;
                                        name?: string | null;
                                        role?: string | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'avatarAtom';
                                      }
                                    | {
                                        label?: string | null;
                                        variant?: ('default' | 'secondary' | 'outline' | 'destructive') | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'badgeAtom';
                                      }
                                    | {
                                        label: string;
                                        url?: string | null;
                                        variant?:
                                          | ('default' | 'secondary' | 'outline' | 'ghost' | 'destructive')
                                          | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'buttonAtom';
                                      }
                                    | {
                                        title?: string | null;
                                        description?: string | null;
                                        image?: (string | null) | Media;
                                        link?: string | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'cardAtom';
                                      }
                                    | {
                                        slides?:
                                          | {
                                              image?: (string | null) | Media;
                                              caption?: string | null;
                                              id?: string | null;
                                            }[]
                                          | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'carouselAtom';
                                      }
                                    | {
                                        /**
                                         * Lucide icon name
                                         */
                                        iconName?: string | null;
                                        size?: number | null;
                                        /**
                                         * Tailwind class or Hex
                                         */
                                        color?: string | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'iconAtom';
                                      }
                                    | {
                                        image: string | Media;
                                        aspect?: ('square' | 'video' | 'wide') | null;
                                        caption?: string | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'imageAtom';
                                      }
                                    | {
                                        value?: number | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'progressAtom';
                                      }
                                    | {
                                        spacing?: ('sm' | 'md' | 'lg' | 'xl') | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'separatorAtom';
                                      }
                                    | {
                                        /**
                                         * Select a preset spacing value, or choose "None" to set custom values
                                         */
                                        spacing?: ('none' | '8' | '16' | '24') | null;
                                        top?: number | null;
                                        bottom?: number | null;
                                        left?: number | null;
                                        right?: number | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'spacerAtom';
                                      }
                                    | {
                                        rows?:
                                          | {
                                              cells?:
                                                | {
                                                    value?: string | null;
                                                    id?: string | null;
                                                  }[]
                                                | null;
                                              id?: string | null;
                                            }[]
                                          | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'tableAtom';
                                      }
                                    | {
                                        tabs?:
                                          | {
                                              label?: string | null;
                                              content?: string | null;
                                              id?: string | null;
                                            }[]
                                          | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'tabsAtom';
                                      }
                                    | {
                                        content?: {
                                          root: {
                                            type: string;
                                            children: {
                                              type: any;
                                              version: number;
                                              [k: string]: unknown;
                                            }[];
                                            direction: ('ltr' | 'rtl') | null;
                                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                            indent: number;
                                            version: number;
                                          };
                                          [k: string]: unknown;
                                        } | null;
                                        align?: ('left' | 'center' | 'right') | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'textAtom';
                                      }
                                    | {
                                        url: string;
                                        controls?: boolean | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'videoAtom';
                                      }
                                    | {
                                        form: string | Form;
                                        enableIntro?: boolean | null;
                                        introContent?: {
                                          root: {
                                            type: string;
                                            children: {
                                              type: any;
                                              version: number;
                                              [k: string]: unknown;
                                            }[];
                                            direction: ('ltr' | 'rtl') | null;
                                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                            indent: number;
                                            version: number;
                                          };
                                          [k: string]: unknown;
                                        } | null;
                                        useContainer?: ('yes' | 'no') | null;
                                        id?: string | null;
                                        blockName?: string | null;
                                        blockType: 'formBlock';
                                      }
                                  )[]
                                | null;
                              id?: string | null;
                              blockName?: string | null;
                              blockType: 'gridItem';
                            }[]
                          | null;
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'gridArea';
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'container';
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'buildYourOwnSection';
          }
        | {
            sectionTitle?: string | null;
            title?: string | null;
            description?: string | null;
            items: {
              trackId?: string | null;
              question: string;
              answer: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            columns?: ('2' | '3' | '4') | null;
            features?:
              | {
                  title?: string | null;
                  description?: string | null;
                  badge?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            heading?: string | null;
            tabs?:
              | {
                  label: string;
                  title?: string | null;
                  description?: string | null;
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureTabs';
          }
        | FormBlock
        | {
            variant: 'full' | 'split';
            heading: string;
            subheading?: string | null;
            image: string | Media;
            actions?:
              | {
                  label: string;
                  link: string;
                  style?: ('default' | 'outline' | 'ghost') | null;
                  /**
                   * Optional unique identifier for click tracking
                   */
                  trackId?: string | null;
                  id?: string | null;
                }[]
              | null;
            pillText?: string | null;
            /**
             * Adds a dark translucent overlay and blur effect over the background image
             */
            backdrop?: boolean | null;
            splitSettings?: {
              theme?: ('light' | 'dark') | null;
              imagePosition?: ('left' | 'right') | null;
            };
            /**
             * Optional unique identifier for this hero section
             */
            sectionId?: string | null;
            containerSettings?: {
              useContainer?: boolean | null;
              containerSize?: ('sm' | 'md' | 'lg' | 'full') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBanner';
          }
        | {
            mediaType: 'image' | 'pdf' | 'video';
            image?: (string | null) | Media;
            pdf?: (string | null) | Media;
            video?: (string | null) | Media;
            caption?: string | null;
            showCard?: boolean | null;
            /**
             * Select a preset aspect ratio, or choose "None" to set custom width/height.
             */
            ratio?: ('none' | '1:1' | '4:3' | '16:9' | '21:9') | null;
            width?: number | null;
            height?: number | null;
            containerSettings?: {
              useContainer?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaViewer';
          }
        | {
            heading?: string | null;
            plans?:
              | {
                  name: string;
                  price: string;
                  description?: string | null;
                  isPopular?: boolean | null;
                  features?:
                    | {
                        feature?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  buttonText?: string | null;
                  buttonLink?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingTable';
          }
        | RichTextContentBlock
        | {
            title?: string | null;
            sourceType?: ('static' | 'api') | null;
            headers?:
              | {
                  label?: string | null;
                  id?: string | null;
                }[]
              | null;
            rows?:
              | {
                  cells?:
                    | {
                        value?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            apiUrl?: string | null;
            /**
             * Map JSON keys to Table Headers
             */
            columnMapping?:
              | {
                  header: string;
                  dataKey: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'smartTable';
          }
        | {
            title?: string | null;
            reviews?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  avatar?: (string | null) | Media;
                  rating?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialCarousel';
          }
        | {
            heading?: string | null;
            events?:
              | {
                  year: string;
                  title?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * If true, this page is a variant served only via an Experiment. Direct visits to this page will return 404.
   */
  isVariant?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            basePrice?: number | null;
            priceConditions?:
              | {
                  fieldToUse?: string | null;
                  condition?: ('hasValue' | 'equals' | 'notEquals') | null;
                  valueForCondition?: string | null;
                  operator?: ('add' | 'subtract' | 'multiply' | 'divide') | null;
                  valueType?: ('static' | 'valueOfField') | null;
                  valueForOperator?: string | null;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'payment';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'radio';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'date';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  useContainer?: ('yes' | 'no') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextContentBlock".
 */
export interface RichTextContentBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richtext-content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiments".
 */
export interface Experiment {
  id: string;
  name: string;
  /**
   * Public route where the experiment runs (e.g. "landing")
   */
  slug: string;
  /**
   * Unique experiment identifier for hashing/analytics
   */
  experimentId: string;
  enabled?: boolean | null;
  variants: {
    page: string | Page;
    weight: number;
    /**
     * Optional label for analytics (e.g. "control")
     */
    label?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  payment?: {
    field?: string | null;
    status?: string | null;
    /**
     * Amount in cents
     */
    amount?: number | null;
    paymentProcessor?: string | null;
    creditCard?: {
      token?: string | null;
      brand?: string | null;
      number?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'pages';
    value: string | Page;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: string;
  /**
   * The user that the API key is associated with.
   */
  user: string | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  posts?: {
    /**
     * Allow clients to find posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create posts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update posts.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete posts.
     */
    delete?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'experiments';
        value: string | Experiment;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  parent?: T;
  fullSlug?: T;
  title?: T;
  layout?:
    | T
    | {
        banner?: T | BannerBlockSelect<T>;
        bentoGrid?:
          | T
          | {
              trackId?: T;
              title?: T;
              cards?:
                | T
                | {
                    title?: T;
                    content?: T;
                    icon?: T;
                    span?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        buildYourOwnSection?:
          | T
          | {
              container?:
                | T
                | {
                    container?:
                      | T
                      | {
                          width?: T;
                          padding?: T;
                          areas?:
                            | T
                            | {
                                gridArea?:
                                  | T
                                  | {
                                      justify?: T;
                                      align?: T;
                                      gap?: T;
                                      items?:
                                        | T
                                        | {
                                            gridItem?:
                                              | T
                                              | {
                                                  responsiveWidth?:
                                                    | T
                                                    | {
                                                        base?: T;
                                                        sm?: T;
                                                        md?: T;
                                                        lg?: T;
                                                        xl?: T;
                                                      };
                                                  content?:
                                                    | T
                                                    | {
                                                        accordionAtom?:
                                                          | T
                                                          | {
                                                              items?:
                                                                | T
                                                                | {
                                                                    title?: T;
                                                                    content?: T;
                                                                    id?: T;
                                                                  };
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        alertAtom?:
                                                          | T
                                                          | {
                                                              title?: T;
                                                              description?: T;
                                                              variant?: T;
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        alignerAtom?:
                                                          | T
                                                          | {
                                                              direction?: T;
                                                              justify?: T;
                                                              align?: T;
                                                              gap?: T;
                                                              items?:
                                                                | T
                                                                | {
                                                                    buttonAtom?:
                                                                      | T
                                                                      | {
                                                                          label?: T;
                                                                          url?: T;
                                                                          variant?: T;
                                                                          id?: T;
                                                                          blockName?: T;
                                                                        };
                                                                    iconAtom?:
                                                                      | T
                                                                      | {
                                                                          iconName?: T;
                                                                          size?: T;
                                                                          color?: T;
                                                                          id?: T;
                                                                          blockName?: T;
                                                                        };
                                                                    spacerAtom?:
                                                                      | T
                                                                      | {
                                                                          spacing?: T;
                                                                          top?: T;
                                                                          bottom?: T;
                                                                          left?: T;
                                                                          right?: T;
                                                                          id?: T;
                                                                          blockName?: T;
                                                                        };
                                                                    textAtom?:
                                                                      | T
                                                                      | {
                                                                          content?: T;
                                                                          align?: T;
                                                                          id?: T;
                                                                          blockName?: T;
                                                                        };
                                                                  };
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        avatarAtom?:
                                                          | T
                                                          | {
                                                              image?: T;
                                                              name?: T;
                                                              role?: T;
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        badgeAtom?:
                                                          | T
                                                          | {
                                                              label?: T;
                                                              variant?: T;
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        buttonAtom?:
                                                          | T
                                                          | {
                                                              label?: T;
                                                              url?: T;
                                                              variant?: T;
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        cardAtom?:
                                                          | T
                                                          | {
                                                              title?: T;
                                                              description?: T;
                                                              image?: T;
                                                              link?: T;
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        carouselAtom?:
                                                          | T
                                                          | {
                                                              slides?:
                                                                | T
                                                                | {
                                                                    image?: T;
                                                                    caption?: T;
                                                                    id?: T;
                                                                  };
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        iconAtom?:
                                                          | T
                                                          | {
                                                              iconName?: T;
                                                              size?: T;
                                                              color?: T;
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        imageAtom?:
                                                          | T
                                                          | {
                                                              image?: T;
                                                              aspect?: T;
                                                              caption?: T;
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        progressAtom?:
                                                          | T
                                                          | {
                                                              value?: T;
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        separatorAtom?:
                                                          | T
                                                          | {
                                                              spacing?: T;
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        spacerAtom?:
                                                          | T
                                                          | {
                                                              spacing?: T;
                                                              top?: T;
                                                              bottom?: T;
                                                              left?: T;
                                                              right?: T;
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        tableAtom?:
                                                          | T
                                                          | {
                                                              rows?:
                                                                | T
                                                                | {
                                                                    cells?:
                                                                      | T
                                                                      | {
                                                                          value?: T;
                                                                          id?: T;
                                                                        };
                                                                    id?: T;
                                                                  };
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        tabsAtom?:
                                                          | T
                                                          | {
                                                              tabs?:
                                                                | T
                                                                | {
                                                                    label?: T;
                                                                    content?: T;
                                                                    id?: T;
                                                                  };
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        textAtom?:
                                                          | T
                                                          | {
                                                              content?: T;
                                                              align?: T;
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        videoAtom?:
                                                          | T
                                                          | {
                                                              url?: T;
                                                              controls?: T;
                                                              id?: T;
                                                              blockName?: T;
                                                            };
                                                        formBlock?: T | FormBlockSelect<T>;
                                                      };
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                          };
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              sectionTitle?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    trackId?: T;
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              columns?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    badge?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureTabs?:
          | T
          | {
              heading?: T;
              tabs?:
                | T
                | {
                    label?: T;
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        formBlock?: T | FormBlockSelect<T>;
        heroBanner?:
          | T
          | {
              variant?: T;
              heading?: T;
              subheading?: T;
              image?: T;
              actions?:
                | T
                | {
                    label?: T;
                    link?: T;
                    style?: T;
                    trackId?: T;
                    id?: T;
                  };
              pillText?: T;
              backdrop?: T;
              splitSettings?:
                | T
                | {
                    theme?: T;
                    imagePosition?: T;
                  };
              sectionId?: T;
              containerSettings?:
                | T
                | {
                    useContainer?: T;
                    containerSize?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaViewer?:
          | T
          | {
              mediaType?: T;
              image?: T;
              pdf?: T;
              video?: T;
              caption?: T;
              showCard?: T;
              ratio?: T;
              width?: T;
              height?: T;
              containerSettings?:
                | T
                | {
                    useContainer?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricingTable?:
          | T
          | {
              heading?: T;
              plans?:
                | T
                | {
                    name?: T;
                    price?: T;
                    description?: T;
                    isPopular?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    buttonText?: T;
                    buttonLink?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'richtext-content'?: T | RichTextContentBlockSelect<T>;
        smartTable?:
          | T
          | {
              title?: T;
              sourceType?: T;
              headers?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              apiUrl?: T;
              columnMapping?:
                | T
                | {
                    header?: T;
                    dataKey?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonialCarousel?:
          | T
          | {
              title?: T;
              reviews?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    avatar?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              heading?: T;
              events?:
                | T
                | {
                    year?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  isVariant?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  useContainer?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextContentBlock_select".
 */
export interface RichTextContentBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiments_select".
 */
export interface ExperimentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  experimentId?: T;
  enabled?: T;
  variants?:
    | T
    | {
        page?: T;
        weight?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        payment?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              basePrice?: T;
              priceConditions?:
                | T
                | {
                    fieldToUse?: T;
                    condition?: T;
                    valueForCondition?: T;
                    operator?: T;
                    valueType?: T;
                    valueForOperator?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        radio?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        date?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  payment?:
    | T
    | {
        field?: T;
        status?: T;
        amount?: T;
        paymentProcessor?: T;
        creditCard?:
          | T
          | {
              token?: T;
              brand?: T;
              number?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  posts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}